client_config_backend: settings
client_config:
  client_id: # Find it in client_secrets.json
  client_secret: # Find it in client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive